version: '3'

services:
  web:
    build: .
    ports: 
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Server=db;Database=todosdb;Uid=root;Pwd=password;SslMode=None;
    entrypoint: bash /app/wait_for_it.sh db:3306 -t 0 -- dotnet /app/TodoService.dll
    depends_on: 
      - db
  db:
    image: mysql
    ports:
      - 3306:3306
    environment: 
      - MYSQL_DATABASE=todosdb
      - MYSQL_ROOT_PASSWORD=password
    volumes: 
      - ./Scripts:/docker-entrypoint-initdb.d
